- alias: QOS - Slow down Transmission when someone's on the server
  trigger:
    - platform: template
      value_template: >
        {{states('sensor.ftb_revelation_server_players_online') | int > 0}}
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.transmission_turtle_mode

- alias: QOS - Speed transmission back up when no one's on the server
  trigger:
    - platform: template
      value_template: >
        {{states('sensor.ftb_revelation_server_players_online') | int == 0}}
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.transmission_turtle_mode
