- alias: Notify - When the Index store page buttons change
  trigger:
    - platform: state
      entity_id: sensor.valve_index_buy_now_button_on_steam_store
  action:
    - service: script.automate_notify
      data_template:
        title: Valve Index buttons changed!
        message: >
          {{trigger.to_state.attributes.value}}
        icon: 61723
