- alias: Speak - When minecraft server player count changes
  trigger:
    - platform: state
      entity_id: sensor.ftb_revelation_server_players_online
  condition:
    - condition: template
      value_template: >
        {{trigger.from_state.state != trigger.to_state.state}}
  action:
    - service: tts.amazon_polly_say
      data_template:
        entity_id: media_player.huawei_cam
        message: >
          {% set from = trigger.from_state.attributes.players_list or [] %}
          {% set to = trigger.to_state.attributes.players_list or [] %}

          {% for player in to %}
            {% if player not in from %}
              {{player}} has joined FTB
            {% endif %}
          {% endfor %}

          {% for player in from %}
            {% if player not in to %}
              {{player}} has left FTB
            {% endif %}
          {% endfor %}
