- alias: Speak - When a Steam friend plays a game
  trigger:
    - platform: state
      entity_id: !secret steam_account_sensors
  action:
    - service: tts.amazon_polly_say
      data_template:
        entity_id: media_player.huawei_cam
        message: >
          {% set game = trigger.to_state.attributes.game %}

          {% if trigger.to_state.state == "online" %}
            {% set action = "came online" %}
          {% elif trigger.to_state.state == "offline" %}
            {% set action = "has gone offline" %}
          {% endif %}

          {{state_attr(trigger.entity_id, 'friendly_name')}}
          {% if game %}
            started playing {{game}}
          {% elif action %}
            {{action}}
          {% else %}
            changed from {{trigger.from_state.state}} to {{trigger.to_state.state}}
          {% endif %}
