- alias: HA - Run git pull on incoming webhook
  trigger:
    platform: webhook
    webhook_id: !secret github_webhook_id
  action:
    - service: shell_command.git_pull
    - service: homeassistant.check_config
    - service: browser_mod.lovelace_reload
    - service: frontend.reload_themes
    - service: automation.reload
    - service: input_boolean.reload
    - service: input_select.reload
    - service: input_datetime.reload
    - service: zone.reload
    - service: script.reload
    - service: scene.reload
    - service: group.reload
    - service: person.reload
    - service: python_script.reload

    - service: automation.turn_on
      entity_id: automation.ha_run_git_pull_on_incoming_webhook

- alias: HA - Turn git pull automation back on on startup
  trigger:
  - event: start
    platform: homeassistant
  action:
  - service: automation.turn_on
    entity_id: automation.ha_run_git_pull_on_incoming_webhook
