- alias: Notify - Service restart
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - service: script.automate_notify
    data:
      message: Home Assistant startup complete

