- alias: Notify - On new liked video
  trigger:
  - event_data:
      action: new_liked_video
    event_type: ifttt_webhook_received
    platform: event
  condition: []
  action:
  - service: notify.notify
    data:
      message: New liked video!
