- alias: Youtube - Record new liked video
  trigger:
  - event_data:
      action: new_liked_video
    event_type: ifttt_webhook_received
    platform: event
  condition: []
  action:
  - service: script.automate_notify
    data_template:
      message: >
        New liked video: {{trigger.event.data.title}}
  - service: var.set
    data_template:
      entity_id: var.last_liked_video
      value: >
        {{trigger.event.data.url}}
