- alias: Notify - On new liked video
  trigger:
  - event_data:
      action: new_liked_video
    event_type: ifttt_webhook_received
    platform: event
  condition: []
  action:
  - service: notify.notify
    data_template:
      message: 'New liked video: {{trigger.event.data.title}}'
  - service: var.set
    data_template:
      entity_id: last_liked_video
      value: '{{trigger.event.data.embedCode}}'
