homeassistant:
  packages:
    health: !include packages/health/index.yaml
    lights: !include packages/lights/index.yaml
    home_assistant: !include packages/home_assistant/index.yaml
    roomba: !include packages/roomba/index.yaml
    plugins: !include packages/plugins/index.yaml
    time: !include packages/time/index.yaml

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes
