homeassistant:
  name: Home

  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_elevation

  # metric or imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_timezone
  customize: !include packages/home_assistant/customize.yaml

  packages:
    health: !include packages/health/index.yaml
    lights: !include packages/lights/index.yaml
    home_assistant: !include packages/home_assistant/index.yaml
    roomba: !include packages/roomba/index.yaml
    miscellaneous: !include packages/miscellaneous/index.yaml
    time: !include packages/time/index.yaml
    weather: !include packages/weather/index.yaml
    youtube: !include packages/youtube/index.yaml
    theater: !include packages/theater/index.yaml
    monitoring: !include packages/monitoring/index.yaml
    gaming: !include packages/gaming/index.yaml
    phone: !include packages/phone/index.yaml

  auth_mfa_modules:
    - type: totp
      name: Authenticator app

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Take X-Forwarded-For from Traefik
http:
  use_x_forwarded_for: true
  trusted_proxies: ***REMOVED***

lovelace:
  mode: yaml
