title: Home

views:
  - !include lovelace/views/home.yaml
  - !include lovelace/views/lights.yaml
  - !include lovelace/views/monitoring.yaml
  - !include lovelace/views/gaming.yaml
  - !include lovelace/views/health.yaml
  - !include lovelace/views/entertainment.yaml
  - !include lovelace/views/guest.yaml
  - !include lovelace/views/settings.yaml
  - !include lovelace/views/sandbox.yaml
