resources:
  - type: module
    url: >-
      https://cdn.jsdelivr.net/gh/bramkragten/weather-card/dist/weather-card.min.js
  - type: module
    url: /community_plugin/lovelace-animated-background/animated-background.js
  - type: module
    url: /community_plugin/button-card/button-card.js
  - type: js
    url: /community_plugin/username-element/username-element.js
  - type: module
    url: /community_plugin/radial-menu/radial-menu.js
  - type: module
    url: /community_plugin/swipe-card/swipe-card.js
  - type: module
    url: /community_plugin/lovelace-gui-sandbox/gui-sandbox.js
  - type: module
    url: /community_plugin/lovelace-card-mod/card-mod.js
  - type: module
    url: /community_plugin/button-entity-row/button-entity-row.js
  - type: module
    url: /community_plugin/circle-sensor-card/circle-sensor-card.js
  - type: module
    url: /community_plugin/swipe-glance-card/swipe-glance-card.js
  - type: module
    url: /community_plugin/config-template-card/config-template-card.js
  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js

title: Home

views:
  - badges:
      - entity: device_tracker.decentm_phone
      - entity: sensor.hacs
      - entity: binary_sensor.updater
    cards:
      - entity: var.roomba_dirty_runs
        max: 4
        min: 0
        name: Dirty runs
        severity:
          green: 0
          red: 4
          yellow: 3
        theme: default
        type: gauge
      - columns: 3
        entities:
          - entity: light.bed
            tap_action:
              action: toggle
          - entity: light.workstation
            tap_action:
              action: toggle
          - entity: light.kitchen_wall
            tap_action:
              action: toggle
        show_icon: true
        show_name: true
        show_state: false
        type: glance
      - entities:
          - entity: vacuum.roomba
        type: entities
      - entities:
          - entity: !secret sensor_air_quality
          - entity: sun.sun
          - entity: sensor.uptime_days
        show_icon: true
        show_name: false
        show_state: true
        type: glance
      - card:
          entities:
            - entity: light.huawei_cam
              name: Huawei cam
          type: entities
        conditions:
          - entity: light.huawei_cam
            state_not: unavailable
        type: conditional
      - entity: weather.dark_sky
        type: weather-forecast
      - entities:
          - entity: binary_sensor.openusercss_10_seconds_load_time
            name: OUC 10s
          - entity: binary_sensor.openusercss_5_seconds_load_time
            name: OUC 5s
          - entity: binary_sensor.matomo_archival
            name: Matomo arch.
        hours_to_show: 24
        refresh_interval: 0
        title: Cloud services
        type: history-graph
      - entities:
          - entity: sensor.seventeentrack_packages_in_transit
          - entity: sensor.seventeentrack_packages_not_found
          - entity: sensor.seventeentrack_packages_delivered
        type: entities
      - card:
          aspect_ratio: 50%
          type: iframe
          url: '${vars[0].split("youtu.be").join("www.youtube.com/embed")}'
        entities: []
        type: 'custom:config-template-card'
        variables:
          - 'states[''var.last_liked_video''].state'
    icon: 'mdi:lightbulb'
    panel: false
    path: lights
    title: Lights
  - badges: []
    cards:
      - entity: !secret sensor_withings_systolic
        max: 180
        min: 120
        name: Systolic
        severity:
          green: 120
          red: 140
          yellow: 130
        theme: default
        type: gauge
        unit: ' '
      - entity: !secret sensor_withings_systolic
        max: 110
        min: 80
        name: Diastolic
        severity:
          green: 80
          red: 90
          yellow: 85
        theme: default
        type: gauge
        unit: ' '
      - entities:
          - entity: !secret sensor_withings_weight
            name: Weight
          - entity: !secret sensor_withings_hyrdation
            name: Hydration
          - entity: !secret sensor_withings_hr_avg
            name: Sleeping pulse
          - entity: !secret sensor_withings_systolic
            name: Systolic blood pressure
          - entity: !secret sensor_withings_diastolic
            name: Diastolic blood pressure
          - entity: !secret sensor_withings_pulse
            name: Pulse
        type: entities
      - type: 'custom:mini-graph-card'
        entities:
          - null
    icon: 'mdi:heart'
    title: Health
  - badges: []
    cards:
      - entity: var.roomba_dirty_runs
        max: 4
        min: 0
        name: Dirty runs
        severity:
          green: 0
          red: 4
          yellow: 3
        theme: default
        type: gauge
    icon: 'mdi:view-dashboard'
    path: tiny-dashboard
    title: Tiny dashboard
