title: Home

resources: !include lovelace/resources.yaml
custom_header: !include lovelace/custom_header/index.yaml

views:
  - !include lovelace/views/home.yaml
  - !include lovelace/views/time.yaml
  - !include lovelace/views/entertainment.yaml
  - !include lovelace/views/health.yaml
  - !include lovelace/views/tiny.yaml
  - !include lovelace/views/guest.yaml
  - !include lovelace/views/sandbox.yaml
