- alias: Lights - All lights off when I leave home
  trigger:
    - platform: state
      entity_id: device_tracker.decentm_phone
      from: home
      to: away
  condition:
  - condition: state
    entity_id: light.all_lights
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.all_lights
  - service: script.automate_notify
    data:
      title: Lights turned off
      message: Some lights have been turned off after you left.
      icon: 61518
