- alias: Lights - Turn all lights off when I get in bed
  trigger:
    - platform: state
      entity_id: switch.in_bed
      from: 'off'
      to: 'on'
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.all_lights
      transition: 5

- alias: Lights - Turn some lights on when I get ouf of bed in the dark
  trigger:
  - platform: state
    entity_id: switch.in_bed
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: light.turn_on
    data:
      entity_id:
        - light.bed
        - light.kitchen_wall
        - light.bathroom
      transition: 10
      brightness: 20
