- platform: template
  sensors:
    # Middle
    deconz_event_type_ikea_remote_middle_hold:
      friendly_name: >
        deCONZ event type for IKEA TRÅDFRI five-button remote - middle button,
        continuous hold
      value_template: 1001

    deconz_event_type_ikea_remote_middle_short:
      friendly_name: >
        deCONZ event type for IKEA TRÅDFRI five-button remote - middle button,
        short release
      value_template: 1002

    deconz_event_type_ikea_remote_middle_short:
      friendly_name: >
        deCONZ event type for IKEA TRÅDFRI five-button remote - middle button,
        long release
      value_template: 1003

    # Up
    deconz_event_type_ikea_remote_up_hold:
      friendly_name: >
        deCONZ event type for IKEA TRÅDFRI five-button remote - up button,
        continuous hold
      value_template: 2001

    deconz_event_type_ikea_remote_up_short:
      friendly_name: >
        deCONZ event type for IKEA TRÅDFRI five-button remote - up button,
        short release
      value_template: 2002

    deconz_event_type_ikea_remote_up_short:
      friendly_name: >
        deCONZ event type for IKEA TRÅDFRI five-button remote - up button,
        long release
      value_template: 2003

    # Down
    deconz_event_type_ikea_remote_down_hold:
      friendly_name: >
        deCONZ event type for IKEA TRÅDFRI five-button remote - down button,
        continuous hold
      value_template: 3001

    deconz_event_type_ikea_remote_down_short:
      friendly_name: >
        deCONZ event type for IKEA TRÅDFRI five-button remote - down button,
        short release
      value_template: 3002

    deconz_event_type_ikea_remote_down_short:
      friendly_name: >
        deCONZ event type for IKEA TRÅDFRI five-button remote - down button,
        long release
      value_template: 3003

    # Left
    deconz_event_type_ikea_remote_left_hold:
      friendly_name: >
        deCONZ event type for IKEA TRÅDFRI five-button remote - left button,
        continuous hold
      value_template: 4001

    deconz_event_type_ikea_remote_left_short:
      friendly_name: >
        deCONZ event type for IKEA TRÅDFRI five-button remote - left button,
        short release
      value_template: 4002

    deconz_event_type_ikea_remote_left_short:
      friendly_name: >
        deCONZ event type for IKEA TRÅDFRI five-button remote - left button,
        long release
      value_template: 4003

    # Right
    deconz_event_type_ikea_remote_right_hold:
      friendly_name: >
        deCONZ event type for IKEA TRÅDFRI five-button remote - right button,
        continuous hold
      value_template: 5001

    deconz_event_type_ikea_remote_right_short:
      friendly_name: >
        deCONZ event type for IKEA TRÅDFRI five-button remote - right button,
        short release
      value_template: 5002

    deconz_event_type_ikea_remote_right_short:
      friendly_name: >
        deCONZ event type for IKEA TRÅDFRI five-button remote - right button,
        long release
      value_template: 5003
