- alias: Light switches - Bathroom remote, middle button
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bathroom_remote
      event: 1002
  condition: []
  action:
    service: light.toggle
    entity_id: light.bathroom_ceiling

- alias: Light switches - Bathroom remote, up button
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bathroom_remote
      event: 2002
  condition: []
  action:
    service: light.turn_on
    entity_id: light.bathroom_ceiling
    data_template:
      brightness: >
        {% if states.light.bathroom_ceiling.attributes.brightness %}
          {{states.light.bathroom_ceiling.attributes.brightness + 25}}
        {% else %}
          25
        {% endif %}

- alias: Light switches - Bathroom remote, down button
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bathroom_remote
      event: 3002
  condition: []
  action:
    service: light.turn_on
    entity_id: light.bathroom_ceiling
    data_template:
      brightness: >
        {% if states.light.bathroom_ceiling.attributes.brightness %}
          {{states.light.bathroom_ceiling.attributes.brightness - 25}}
        {% else %}
          220
        {% endif %}
