- alias: Light switches - Kitchen remote, up button
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_on_off_switch
      event: "{{states.sensor.deconz_event_type_ikea_remote_up_short}}"
  condition: []
  action:
    service: light.turn_on
    entity_id: light.kitchen_ceiling

- alias: Light switches - Kitchen remote, down button
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_on_off_switch
      event: "{{states.sensor.deconz_event_type_ikea_remote_down_short}}"
  condition: []
  action:
    service: light.turn_off
    entity_id: light.kitchen_ceiling
