- alias: Light switches - Kitchen remote, up button
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_on_off_switch
      event: 1002
  condition: []
  action:
    service: light.turn_on
    entity_id: light.kitchen_ceiling

- alias: Light switches - Kitchen remote, down button
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_on_off_switch
      event: 2002
  condition: []
  action:
    service: light.turn_off
    entity_id: light.kitchen_ceiling
