- alias: Light switches - Kitchen remote, up button
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_on_off_switch
      event: 1002
  condition: []
  action:
    service: light.turn_on
    entity_id: light.kitchen_ceiling

- alias: Light switches - Kitchen remote, up button hold
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_on_off_switch
      event: 1001
  condition: []
  action:
    service: light.turn_on
    data_template:
      entity_id: light.kitchen_ceiling
      brightness: 254
      transition: 0.66667

- alias: Light switches - Kitchen remote, down button
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_on_off_switch
      event: 2002
  condition: []
  action:
    service: light.turn_off
    entity_id: light.kitchen_ceiling

- alias: Light switches - Kitchen remote, down button hold
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_on_off_switch
      event: 2001
  condition: []
  action:
    service: light.turn_on
    data_template:
      entity_id: light.kitchen_ceiling
      brightness: 20
      transition: 0.66667
