- alias: Light switches - Remote 1, middle button
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: remote_1
      event: 1002
  action:
    service: light.toggle
    data_template:
      entity_id: >
        {{states('input_select.remote_binding_1')}}

- alias: Light switches - Remote 1, up button short press
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: remote_1
      event: 2002
  action:
    service: light.turn_on
    data_template:
      entity_id: >
        {{states('input_select.remote_binding_1')}}
      brightness: >
        {% if state_attr(states('input_select.remote_binding_1'), 'brightness') %}
          {{state_attr(states('input_select.remote_binding_1'), 'brightness') + 25}}
        {% else %}
          25
        {% endif %}
      transition: 0.33333

- alias: Light switches - Remote 1, up button hold
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: remote_1
      event: 2001
  action:
    service: light.turn_on
    data_template:
      entity_id: >
        {{states('input_select.remote_binding_1')}}
      brightness: 254
      transition: 0.66667

- alias: Light switches - Remote 1, down button short press
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: remote_1
      event: 3002
  action:
    service: light.turn_on
    data_template:
      entity_id: >
        {{states('input_select.remote_binding_1')}}
      brightness: >
        {% if state_attr(states('input_select.remote_binding_1'), 'brightness') %}
          {{state_attr(states('input_select.remote_binding_1'), 'brightness') - 25}}
        {% else %}
          220
        {% endif %}
      transition: 0.33333

- alias: Light switches - Remote 1, down button hold
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: remote_1
      event: 3001
  action:
    service: light.turn_on
    data_template:
      entity_id: >
        {{states('input_select.remote_binding_1')}}
      brightness: 20
      transition: 0.66667

- alias: Light switches - Remote 1, left button
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: remote_1
      event: 4002
  action:
    service: input_select.select_previous
    entity_id: input_select.remote_binding_1

- alias: Light switches - Remote 1, right button
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: remote_1
      event: 5002
  action:
    service: input_select.select_next
    entity_id: input_select.remote_binding_1

- alias: Lights - Identify light target changes for remote 1
  trigger:
    platform: state
    entity_id: input_select.remote_binding_1
  action:
    - service: tts.amazon_polly_say
      data_template:
        entity_id: media_player.huawei_cam
        message: >
          {{state_attr(states('input_select.remote_binding_1'), 'friendly_name')}}
