- alias: Light switches - Bedroom remote, middle button
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_remote
      event: 1002
  condition: []
  action:
    service: light.toggle
    entity_id: light.bedroom_ceiling

- alias: Light switches - Bedroom remote, up button
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_remote
      event: 2002
  condition: []
  action:
    service: light.turn_on
    entity_id: light.bedroom_ceiling
    data_template:
      brightness: >
        {% if states.light.bedroom_ceiling.attributes.brightness %}
          {{states.light.bedroom_ceiling.attributes.brightness + 25}}
        {% else %}
          25
        {% endif %}

- alias: Light switches - Bedroom remote, down button
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_remote
      event: 3002
  condition: []
  action:
    service: light.turn_on
    entity_id: light.bedroom_ceiling
    data_template:
      brightness: >
        {% if states.light.bedroom_ceiling.attributes.brightness %}
          {{states.light.bedroom_ceiling.attributes.brightness - 25}}
        {% else %}
          220
        {% endif %}

- alias: Light switches - Remote 2, left button
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: remote_2
      event: 4002
  action:
    service: input_select.select_previous
    entity_id: input_select.remote_binding_2

- alias: Light switches - Remote 2, right button
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: remote_2
      event: 5002
  action:
    service: input_select.select_next
    entity_id: input_select.remote_binding_2

- alias: Lights - Identify light target changes for remote 2
  trigger:
    platform: state
    entity_id: input_select.remote_binding_2
  action:
    service: script.blink_light
    data_template:
      entity_id: >
        {{states('input_select.remote_binding_2')}}
