- platform: command_line
  name: Valve Index buy now button on Steam store
  command: bash /config/shell_scripts/web-scrape.sh https://store.steampowered.com/valveindex '.game_purchase_action text{}'
  command_timeout: 30
  scan_interval: 150 # = 2.5 minutes
  value_template: "{{value}}"
