- alias: Automate - Receive feedback and route to script
  trigger:
    platform: webhook
    webhook_id: !secret automate_webhook_id
  condition:
    - condition: template
      value_template: >
        {{trigger.json.feedback_script != None}}
  action:
    service_template: >
      script.{{trigger.json.feedback_script}}
    data_template:
      data: "{{trigger.json}}"
