vacuum:
  - platform: roomba
    host: !secret vacuum_host
    username: !secret vacuum_username
    password: !secret vacuum_password

automation: !include_dir_merge_list automations

# Custom variables
input_number: !include_dir_named input_numbers
