roomba:
  host: !secret vacuum_host
  blid: !secret vacuum_username
  password: !secret vacuum_password
  continuous: false

automation: !include_dir_merge_list automations

# Custom variables
input_number: !include_dir_named input_numbers
