- alias: Notify - When vacuuming is skipped due to dirty tray
  description: ''
  trigger:
  - at: '10:45'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: numeric_state
    entity_id: var.roomba_dirty_runs
    above: 4
  action:
  - service: script.automate_notify
    data:
      icon: 61624
      title: Vacuuming
      message: Vacuuming skipped as the tray hasn't been cleaned in a while

- alias: Notify - When vacuuming begins
  description: ''
  trigger:
  - entity_id: vacuum.roomba
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - service: script.automate_notify
    data:
      icon: 61624
      title: Vacuuming
      message: Vacuuming started

- alias: Notify - When roomba is charging after being shut off
  description: ''
  trigger:
  - entity_id: vacuum.roomba
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - wait_template: '{{ state_attr(''vacuum.roomba'', ''status'') == ''Charging'' }}'
    continue_on_timeout: false
  - service: script.automate_notify
    data:
      icon: 61624
      title: Vacuuming
      message: Roomba is now charging

- alias: Notify - When vacuuming is cancelled
  description: ''
  trigger:
  - entity_id: vacuum.roomba
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: template
    value_template: '{{ state_attr(''vacuum.roomba'', ''status'') == ''User Docking'' }}'
  action:
  - service: script.automate_notify
    data:
      icon: 61624
      title: Vacuuming
      message: Roomba was asked to return to station

- alias: Notify - When vacuuming fails
  description: ''
  trigger:
  - entity_id: vacuum.roomba
    for: 00:01:00
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: or
    conditions:
    - condition: template
      value_template: '{{ state_attr(''vacuum.roomba'', ''status'') == ''Stopped'' }}'
    - condition: template
      value_template: '{{ state_attr(''vacuum.roomba'', ''status'') == ''Stuck'' }}'
  action:
  - service: script.automate_notify
    data:
      icon: 61624
      title: Vacuuming
      message: >
        Vacuuming failed, status: state_attr('vacuum.roomba', 'status')
