- platform: command_line
  name: Accuweather
  command: bash /config/shell_scripts/accuweather_alerts.sh accuweather_url
  command_timeout: 30
  scan_interval: 900 # = 15 minutes
  json_attributes:
    - alert1
    - alert2
    - topBanner
    - midBanner
    - forecast
    - countdown
    - timestamp


- platform: template
  sensors:
    accuweather_active_alert_left:
      friendly_name: AccuWeather - Active alert - left
      value_template: "{{state_attr('sensor.accuweather', 'alert1')}}"
    accuweather_active_alert_right:
      friendly_name: AccuWeather - Active alert - right
      value_template: "{{state_attr('sensor.accuweather', 'alert2')}}"
    accuweather_forecast:
      friendly_name: AccuWeather - Forecast
      value_template: "{{state_attr('sensor.accuweather', 'forecast')}}"
