- platform: command_line
  name: Active weather warning - left
  command: bash /config/shell_scripts/accuweather_alerts.sh accuweather_url warnings
  command_timeout: 30
  scan_interval: 3600 # 3600 seconds = 1 hour
  value_template: '{{value_json.warning1}}'

- platform: command_line
  name: Active weather warning - right
  command: bash /config/shell_scripts/accuweather_alerts.sh accuweather_url warnings
  command_timeout: 30
  scan_interval: 3600 # 3600 seconds = 1 hour
  value_template: '{{value_json.warning2}}'

- platform: command_line
  name: Weather banner
  command: bash /config/shell_scripts/accuweather_alerts.sh accuweather_url banner
  command_timeout: 30
  scan_interval: 3600 # 3600 seconds = 1 hour
  value_template: '{{value_json.banner}}'

- platform: command_line
  name: Weather forecast
  command: bash /config/shell_scripts/accuweather_alerts.sh accuweather_url forecast
  command_timeout: 30
  scan_interval: 3600 # 3600 seconds = 1 hour
  value_template: '{{value_json.forecast}}'
