- platform: command_line
  name: Active weather warnings
  # https://community.home-assistant.io/t/using-secrets-yaml-with-shell-commands/4478/9
  command: bash /config/shell_scripts/accuweather_alerts.sh accuweather_url warnings
  command_timeout: 30
  scan_interval: 3600 # 3600 seconds = 1 hour
  value_template: '{{value_json.warning1}}, {{value_json.warning2}}'
  json_attributes:
    - warning1
    - warning2
