- platform: template
  sensors:
    next_wakeup:
      friendly_name: Next wakeup
      value_template: >
        {% set current = utcnow().timestamp() %}
        {% set day = as_timestamp('1970-01-02 00:00:00') %}
        {% set today = as_timestamp(utcnow().strftime("%Y-%m-%d") + " 00:00:00") %}
        {% set wake_hours = as_timestamp("1970-01-01 " + states('input_datetime.wakeup_time')) %}
        {% set next_wake_at = today + 1*day + wake_hours %}

        {{next_wake_at | timestamp_utc}}

      attribute_templates:
        in_hours: >
          {% set current = utcnow().timestamp() %}
          {% set day = as_timestamp('1970-01-02 00:00:00') %}
          {% set today = as_timestamp(utcnow().strftime("%Y-%m-%d") + " 00:00:00") %}
          {% set wake_hours = as_timestamp("1970-01-01 " + states('input_datetime.wakeup_time') + states('input_select.timezone')) %}
          {% set next_wake_at = today + 1*day + wake_hours %}
          {% set next_wake_in = next_wake_at - current %}

          {% set next_wake_in_hours = next_wake_in / 60 / 60 %}

          {{next_wake_in_hours}}

        in_minutes: >
          {% set current = utcnow().timestamp() %}
          {% set day = as_timestamp('1970-01-02 00:00:00') %}
          {% set today = as_timestamp(utcnow().strftime("%Y-%m-%d") + " 00:00:00") %}
          {% set wake_hours = as_timestamp("1970-01-01 " + states('input_datetime.wakeup_time') + states('input_select.timezone')) %}
          {% set next_wake_at = today + 1*day + wake_hours %}
          {% set next_wake_in = next_wake_at - current %}

          {% set next_wake_in_minutes = next_wake_in / 60 %}

          {{next_wake_in_minutes}}
