- alias: Loop - Reply to loop tick event
  trigger:
    - platform: event
      event_type: loop_tick
  condition:
    - condition: template
      value_template: >
        {{states('input_text.last_loop_stop_id') != trigger.event.data.id}}
  action:
    - delay:
        seconds: >
          {{trigger.event.data.delay_seconds | default(1, true)}}
    - service: script.loop_tick
      data_template:
        id: >
          {{trigger.event.data.id}}
        delay_seconds: >
          {{trigger.event.data.delay_seconds}}
