- alias: Lights - Max brightness feedback - Bathroom ceiling
  trigger:
    platform: numeric_state
    entity_id: light.bathroom_ceiling
    value_template: >
      {{state.attributes.brightness}}
    above: 254
  condition: []
  action:
    service: light.turn_on
    entity_id: light.bathroom_ceiling
    data:
      brightness: 240
