hue:
  bridges:
    - host: !secret hue_bridge_ip

tradfri:
  host: !secret tradfri_host

# Example configuration.yaml entry
light:
  - platform: group
    name: Kitchen
    entities:
      - light.kitchen_ceiling_a
      - light.kitchen_ceiling_b
      - light.kitchen_ceiling_c

automation: !include_dir_merge_list automations
