light:
  - platform: group
    name: Kitchen ceiling
    entities:
      - light.kitchen_ceiling_a
      - light.kitchen_ceiling_b
      - light.kitchen_ceiling_c

automation: !include_dir_merge_list automations
input_select: !include_dir_named input_selects
script: !include_dir_named scripts
