hue:
  bridges:
    - host: !secret hue_bridge_ip

tradfri:
  host: !secret tradfri_host

# Example configuration.yaml entry
light:
  - platform: group
    name: All lights
    entities:
      - light.bed
      - light.kitchen_wall
      - light.workstation
      - light.bathroom
      - light.hall
      - light.kitchen_spot_1
      - light.kitchen_spot_2
      - light.kitchen_spot_3

automation: !include_dir_merge_list automations
