light:
  - platform: group
    name: Kitchen
    entities:
      - light.kitchen_ceiling_a
      - light.kitchen_ceiling_b
      - light.kitchen_ceiling_c

automation: !include_dir_merge_list automations
