- alias: Turn night vision on in the dark
  description: ''
  trigger:
  - below: '2'
    entity_id: sensor.huawei_cam_light_level
    platform: numeric_state
  condition: []
  action:
  - data:
      state: 'on'
    service: rest_command.phone_nightvision

- alias: Autolight - Turn night vision off when there is light
  description: ''
  trigger:
  - above: '1.9'
    entity_id: sensor.huawei_cam_light_level
    platform: numeric_state
  condition: []
  action:
  - data:
      state: 'off'
    service: rest_command.phone_nightvision
