withings:
  client_id: !secret withings_client_id
  client_secret: !secret withings_client_secret
  profiles:
    - !secret withings_user_profile

automation: !include_dir_merge_list automations
sensor: !include_dir_merge_list sensors

input_boolean: !include_dir_named input_booleans
input_datetime: !include_dir_named input_datetimes
script: !include_dir_named scripts

logbook:
  exclude:
    entities:
      - automation.update_wake_up_sensor_every_minute
      - sensor.next_wakeup
