- platform: nut
  name: UPS
  host: !secret nut_host
  port: !secret nut_port
  username: !secret nut_username
  password: !secret nut_password
  resources:
    - battery.charge
    - battery.charge.low
    - battery.runtime
    - battery.type
    - input.transfer.high
    - input.transfer.low
    - output.frequency.nominal
    - output.voltage
    - output.voltage.nominal
    - ups.beeper.status
    - ups.delay.shutdown
    - ups.delay.start
    - ups.load
    - ups.power.nominal
    - ups.status
    - ups.status.display
    - ups.timer.shutdown
    - ups.timer.start

- platform: template
  sensors:
    ups_battery_runtime_minutes:
      friendly_name: UPS battery runtime
      unit_of_measurement: m
      value_template: >
        {{(states('sensor.ups_battery_runtime') | int / 60) | round}}
