- platform: nut
  name: UPS
  host: !secret nut_host
  port: !secret nut_port
  username: !secret nut_username
  password: !secret nut_password
  resources:
    - battery.charge
    - battery.charge.low
    - battery.runtime
    - battery.type
    - input.transfer.high
    - input.transfer.low
    - output.frequency.nominal
    - output.voltage
    - output.voltage.nominal
    - ups.beeper.status
    - ups.delay.shutdown
    - ups.delay.start
    - ups.firmware
    - ups.load
    - ups.mfr
    - ups.model
    - ups.power.nominal
    - ups.productid
    - ups.serial
    - ups.status
    - ups.timer.shutdown
    - ups.timer.start
    - ups.vendorid
