- alias: Lights - Turn all lights off when I get in bed
  trigger:
  - event_data:
      action: sleep_status_on
    event_type: ifttt_webhook_received
    platform: event
  condition: []
  action:
  - service: light.turn_off
    entity_id: light.all_lights
    transition: 10

- alias: Lights - Turn some lights on when I get ouf of bed
  trigger:
  - event_data:
      action: sleep_status_off
    event_type: ifttt_webhook_received
    platform: event
  condition: []
  action:
  - service: light.turn_on
    entity_id:
      - light.bed
      - light.workstation
    transition: 10
    brightness: 255
