# Enable controlling client browsers as entities
browser_mod:
  prefix: 'browser_'
  devices:
    61b2a237_9753b5c3:
      name: huawei-cam

sensor: !include_dir_merge_list sensors
automation: !include_dir_merge_list automations

shell_command:
  web_scrape: >
    bash /config/shell_scripts/web-scrape.sh {{url}} {{query}}

tts:
- platform: amazon_polly
  aws_access_key_id: !secret polly_key_id
  aws_secret_access_key: !secret polly_access_key
  region_name: !secret polly_region
  voice: Emma
  engine: neural

device_tracker:
  - platform: luci
    host: !secret openwrt_host
    username: !secret openwrt_username
    password: !secret openwrt_password

google_assistant:
  project_id: !secret google_project_id
  service_account: !include ../../google-service-account.json
  report_state: true

transmission:
  name: Transmission
  scan_interval: 60
  host: !secret transmission_host
  port: !secret transmission_port
  username: !secret transmission_username
  password: !secret transmission_password
