- alias: Notify - When meds have not been taken
  trigger:
    platform: time
    at: '09:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.meds_taken
      state: 'off'
  action:
    - service: script.automate_notify
      data:
        feedback_script: ack_meds_taken
        title: Medication
        message: Pills have not been taken yet!
        icon: 61719
    - service: script.loop_tick
      data:
        id: pills-reminder-blink
        delay_seconds: 2
    - wait_template: >
        {{states('input_boolean.meds_taken') == 'on'}}
    - service: script.loop_stop
      data:
        id: pills-reminder-blink
        delay_seconds: 2

- alias: Autolight - Turn off kitchen wall light after loop stops
  trigger:
    platform: event
    event_type: loop_stopped
    event_data:
      id: pills-reminder-blink
  action:
    - service: light.turn_off
      data:
        entity_id: light.kitchen_wall
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.meds_taken
