- alias: Speak - Waking up soon warning
  trigger:
    - platform: template
      value_template: >
        {{states('sensor.next_wakeup_in') < 10}}
  condition:
    - condition: state
      entity_id: light.workstation
      state: 'on'
    - condition: state
      entity_id: binary_sensor.workday_tomorrow
      state: 'on'
  action:
    - service: tts.amazon_polly_say
      data_template:
        message: >
          You're waking up in {{states('sensor.next_wakeup_in')}} hours
