- alias: Speak - Waking up soon warning
  trigger:
    - platform: time_pattern
      minutes: "/20"
  condition:
    - condition: template
      value_template: >
        {{state_attr('sensor.next_wakeup', 'in_hours') | float < 10}}
    - condition: state
      entity_id: light.workstation
      state: 'on'
    - condition: state
      entity_id: binary_sensor.workday_tomorrow
      state: 'on'
  action:
    - service: tts.amazon_polly_say
      data_template:
        entity_id: media_player.huawei_cam
        message: >
          {% set hours = state_attr('sensor.next_wakeup', 'in_hours') | int %}
          {% set hourPercent = state_attr('sensor.next_wakeup', 'in_hours') | float - hours %}
          {% set minutes = (hourPercent * 60) | round %}

          You're waking up in {{hours}} hours and {{minutes}} minutes
