- alias: Lights - Turn on slowly for gentle wakeup
  trigger:
    - platform: template
      value_template: >
        {{state_attr('sensor.next_wakeup', 'in_minutes') | int < 5}}
  condition:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom_ceiling
        brightness: 255
        transition: 300
